"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Stethoscope, AlertTriangle, Clock, ChevronRight, User, FileText, ArrowLeft, Download, ShieldAlert, Activity, HeartPulse, Hospital } from "lucide-react";

export default function DoctorDashboard() {
  const [queue, setQueue] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState<any | null>(null);
  const [doctors, setDoctors] = useState<any[]>([]);
  const [activeDoctorId, setActiveDoctorId] = useState<string>("");

  useEffect(() => {
    fetch("/api/doctors")
      .then(res => res.json())
      .then(data => {
        if (data.doctors && data.doctors.length > 0) {
          setDoctors(data.doctors);
          setActiveDoctorId(data.doctors[0].id); // default to first seeded doctor
        }
      });
  }, []);

  useEffect(() => {
    if (!activeDoctorId) return;
    setLoading(true);
    fetch(`/api/queue?doctorId=${activeDoctorId}`)
      .then((res) => res.json())
      .then((data) => {
        setQueue(data.queue || []);
        setLoading(false);
      });
  }, [activeDoctorId]);

  const getPriorityBadge = (level: string) => {
    switch (level) {
      case "EMERGENCY":
        return <span className="px-3 py-1 bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-400 rounded-full text-xs font-bold uppercase tracking-wider flex items-center gap-1 w-max"><AlertTriangle size={12}/> Emergency</span>;
      case "MODERATE":
        return <span className="px-3 py-1 bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-400 rounded-full text-xs font-bold uppercase tracking-wider w-max">Moderate</span>;
      default:
        return <span className="px-3 py-1 bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-400 rounded-full text-xs font-bold uppercase tracking-wider w-max">Routine</span>;
    }
  };

  const calculateBMI = (wt: number, ht: number) => {
    if (!wt || !ht) return "N/A";
    const htM = ht / 100;
    return (wt / (htM * htM)).toFixed(1);
  };

  if (selectedReport) {
    const p = selectedReport.patient;
    const r = selectedReport.triageResult;
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-4 sm:p-8 print:bg-white print:p-0">
        <div className="max-w-4xl mx-auto">
          {/* Action Header - Hidden during print */}
          <div className="flex items-center justify-between mb-6 print:hidden">
            <button 
              onClick={() => setSelectedReport(null)}
              className="flex items-center gap-2 px-4 py-2 text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white font-medium transition-colors"
            >
              <ArrowLeft size={18} /> Back to Queue
            </button>
            <button 
              onClick={() => window.print()}
              className="flex items-center gap-2 px-6 py-2.5 bg-indigo-600 text-white hover:bg-indigo-700 rounded-xl font-medium shadow-sm transition-all"
            >
              <Download size={18} /> Download PDF
            </button>
          </div>

          <div className="bg-white dark:bg-slate-900 shadow-xl print:shadow-none rounded-3xl print:rounded-none p-8 sm:p-12 print:p-0 print:text-black">
            
            {/* Header Layout */}
            <div className="flex justify-between items-start border-b border-slate-100 dark:border-slate-800 print:border-slate-300 pb-8 mb-8">
              <div>
                <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white print:text-black mb-1">Pre-Consultation Report</h1>
                <p className="text-slate-500 font-medium tracking-wide">Generated by SahayNextgen Triage Engine</p>
              </div>
              <div className="text-right">
                <p className="text-sm text-slate-500 mb-2">Triage Timestamp</p>
                <p className="font-semibold text-slate-900 dark:text-white print:text-black">{new Date(selectedReport.createdAt).toLocaleString()}</p>
              </div>
            </div>

            {/* AI Highlight Banner */}
            <div className={`mb-10 p-6 rounded-2xl border ${r?.priorityLevel === 'EMERGENCY' ? 'bg-rose-50 border-rose-100' : r?.priorityLevel === 'MODERATE' ? 'bg-amber-50 border-amber-100' : 'bg-slate-50 border-slate-100'} dark:bg-slate-800 dark:border-slate-700 print:border-2 print:bg-transparent`}>
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold flex items-center gap-2 text-slate-900 dark:text-white print:text-black">
                  <ShieldAlert className="text-indigo-500" /> AI Triage Assessment
                </h2>
                {getPriorityBadge(r?.priorityLevel || "ROUTINE")}
              </div>
              <div className="space-y-4 text-slate-700 dark:text-slate-300 print:text-black">
                <p><span className="font-semibold text-slate-900 dark:text-white print:text-black">Chief Complaint:</span> {selectedReport.symptoms} <span className="text-sm opacity-70">(Duration: {selectedReport.durationDays} days)</span></p>
                <p><span className="font-semibold text-slate-900 dark:text-white print:text-black ">AI Case Summary:</span> {r?.summary}</p>
                
                {r?.riskFactors && r?.riskFactors !== "None detected" && (
                  <p className="text-rose-700 dark:text-rose-400 print:text-black"><span className="font-bold inline-flex items-center gap-1"><AlertTriangle size={14}/> Detected Risks:</span> {r.riskFactors}</p>
                )}
                
                {r?.careSuggestions && (
                  <div className="mt-4 pt-4 border-t border-slate-200/50 print:border-slate-300">
                    <p className="font-bold text-emerald-700 dark:text-emerald-400 print:text-black mb-1">Precautionary Measures (Pre-Consultation):</p>
                    <p>{r.careSuggestions}</p>
                  </div>
                )}
              </div>
            </div>

            {/* Structured Biological Data */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
              <div className="space-y-8">
                <div>
                  <h3 className="text-lg font-bold flex items-center gap-2 mb-4 border-b pb-2 text-slate-900 dark:text-white print:text-black print:border-slate-300"><User className="text-slate-400"/> Patient Demographics</h3>
                  <div className="space-y-3 text-sm text-slate-700 dark:text-slate-300 print:text-black">
                    <p className="flex justify-between"><span className="text-slate-500 font-medium">Full Name</span> <span className="font-semibold text-slate-900 dark:text-white print:text-black">{p.fullName}</span></p>
                    <p className="flex justify-between"><span className="text-slate-500 font-medium">Age & Gender</span> <span className="font-semibold text-slate-900 dark:text-white print:text-black">{p.age} years, {p.gender}</span></p>
                    <p className="flex justify-between"><span className="text-slate-500 font-medium">Contact</span> <span className="font-semibold text-slate-900 dark:text-white print:text-black">{p.contact || "Undisclosed"}</span></p>
                    <p className="flex justify-between"><span className="text-slate-500 font-medium">Address</span> <span className="font-semibold text-slate-900 dark:text-white print:text-black text-right max-w-[200px] truncate">{p.address || "Undisclosed"}</span></p>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-bold flex items-center gap-2 mb-4 border-b pb-2 text-slate-900 dark:text-white print:text-black print:border-slate-300"><Activity className="text-slate-400"/> Vitals Profile</h3>
                  <div className="space-y-3 text-sm text-slate-700 dark:text-slate-300 print:text-black">
                    <p className="flex justify-between"><span className="text-slate-500 font-medium">Blood Group</span> <span className="font-semibold text-rose-500">{p.bloodGroup || "Unknown"}</span></p>
                    <p className="flex justify-between"><span className="text-slate-500 font-medium">Height / Weight</span> <span className="font-semibold text-slate-900 dark:text-white print:text-black">{p.heightCm} cm / {p.weightKg} kg</span></p>
                    <p className="flex justify-between"><span className="text-slate-500 font-medium">Calculated BMI</span> <span className="font-semibold text-slate-900 dark:text-white print:text-black">{calculateBMI(p.weightKg, p.heightCm)}</span></p>
                  </div>
                </div>
              </div>

              <div>
                <h3 className="text-lg font-bold flex items-center gap-2 mb-4 border-b pb-2 text-slate-900 dark:text-white print:text-black print:border-slate-300"><HeartPulse className="text-slate-400"/> Medical Background</h3>
                <div className="space-y-5 text-sm text-slate-700 dark:text-slate-300 print:text-black">
                  <div>
                    <h4 className="text-slate-500 font-medium mb-1">Past Diseases / Surgeries</h4>
                    <p className="font-medium bg-slate-50 dark:bg-slate-800 p-3 rounded-lg print:bg-transparent print:p-0 print:border-l-2 print:pl-3">{p.pastDiseases || "None reported."}</p>
                  </div>
                  <div>
                    <h4 className="text-slate-500 font-medium mb-1">Chronic Illnesses</h4>
                    <p className="font-medium bg-slate-50 dark:bg-slate-800 p-3 rounded-lg print:bg-transparent print:p-0 print:border-l-2 print:pl-3">{p.chronicIllnesses || "None reported."}</p>
                  </div>
                  <div>
                    <h4 className="text-slate-500 font-medium mb-1">Known Allergies</h4>
                    <p className="font-medium bg-rose-50 dark:bg-rose-900/10 text-rose-700 dark:text-rose-400 p-3 rounded-lg print:bg-transparent print:p-0 print:border-l-2 print:border-rose-500 print:pl-3">{p.allergies || "None reported."}</p>
                  </div>
                  <div>
                    <h4 className="text-slate-500 font-medium mb-1">Family Medical History</h4>
                    <p className="font-medium bg-slate-50 dark:bg-slate-800 p-3 rounded-lg print:bg-transparent print:p-0 print:border-l-2 print:pl-3">{p.familyHistory || "Not disclosed."}</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-12 text-center text-xs text-slate-400 hidden print:block">
              <p>CONFIDENTIAL MEDICAL REPORT — Generated automatically prior to consultation.</p>
              <p>Platform: SahayNextGen Telemedicine Interface</p>
            </div>
            
          </div>
        </div>
      </div>
    );
  }

  const activeDoctorName = doctors.find(d => d.id === activeDoctorId)?.fullName || "Loading Profile...";

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 px-6 py-6 sm:p-10">
      
      {/* Platform Header & MOCK LOGIN SWITCHER */}
      <div className="max-w-6xl mx-auto mb-10 flex flex-col md:flex-row justify-between md:items-center gap-4 bg-indigo-900 p-6 rounded-3xl text-white">
         <div className="flex items-center gap-3">
             <Hospital className="w-8 h-8 text-indigo-300" />
             <div>
                <h2 className="font-bold text-lg leading-tight">Telemedicine Terminal</h2>
                <p className="text-indigo-300 text-sm">Decentralized Queuing System Sandbox</p>
             </div>
         </div>
         <div className="flex items-center gap-3">
             <span className="text-sm font-medium text-indigo-300 block">Simulate viewing as:</span>
             <select 
               value={activeDoctorId} 
               onChange={(e) => setActiveDoctorId(e.target.value)}
               className="bg-indigo-950 border border-indigo-700 text-white rounded-lg px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
             >
               {doctors.map(doc => (
                 <option key={doc.id} value={doc.id}>{doc.fullName} ({doc.specialization})</option>
               ))}
             </select>
         </div>
      </div>

      <div className="max-w-6xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white flex items-center gap-3">
              <Stethoscope className="text-medical-500" /> {activeDoctorName}&apos;s Queue
            </h1>
            <p className="text-slate-500 mt-1">Live securely routed patients for your consultation desk.</p>
          </div>
          <div className="bg-white dark:bg-slate-900 px-4 py-2 rounded-xl shadow-sm border border-slate-100 dark:border-slate-800 text-sm">
             Tracking <span className="font-bold text-slate-900 dark:text-white">{queue.length}</span> Active Cases
          </div>
        </div>

        {loading ? (
          <div className="animate-pulse space-y-4">
            {[1, 2, 3].map(i => (
              <div key={i} className="h-24 bg-white dark:bg-slate-900 rounded-2xl border border-slate-100 dark:border-slate-800"></div>
            ))}
          </div>
        ) : queue.length === 0 ? (
          <div className="bg-white dark:bg-slate-900 p-12 rounded-3xl border border-slate-100 dark:border-slate-800 text-center shadow-sm">
            <User className="w-12 h-12 text-slate-300 mx-auto mb-4" />
            <h3 className="text-xl font-semibold text-slate-900 dark:text-white">Your queue is empty</h3>
            <p className="text-slate-500 mt-2">No patients have shared their pre-consultation report with you yet.</p>
          </div>
        ) : (
          <div className="space-y-4">
            {queue.map((session, idx) => (
              <motion.div 
                key={session.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
                className="bg-white dark:bg-slate-900 p-6 sm:p-8 rounded-2xl border border-slate-100 dark:border-slate-800 shadow-sm flex flex-col md:flex-row md:items-start justify-between gap-6 hover:shadow-md transition-shadow group"
              >
                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-3 mb-3">
                    {getPriorityBadge(session.triageResult?.priorityLevel || "ROUTINE")}
                    <span className="text-sm text-slate-500 flex items-center gap-1 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-md font-medium"><Clock size={12}/> {Math.floor((new Date().getTime() - new Date(session.createdAt).getTime()) / 60000)} mins waiting</span>
                    <span className="text-xs text-slate-400 capitalize">{session.patient?.gender}, {session.patient?.age}</span>
                  </div>
                  <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">{session.patient?.fullName || "Unknown Patient"}</h3>
                  <p className="text-slate-600 dark:text-slate-400 font-medium">Chief Complaint: {session.symptoms}</p>
                  
                  {session.triageResult?.summary && (
                    <div className="mt-4 p-4 bg-indigo-50/50 dark:bg-slate-800/50 rounded-xl border border-indigo-100/50 dark:border-slate-700">
                      <p className="text-sm text-slate-700 dark:text-slate-300">
                        <span className="font-semibold text-indigo-600 dark:text-indigo-400">AI Brief:</span> {session.triageResult.summary}
                      </p>
                    </div>
                  )}
                </div>
                
                <div className="flex md:flex-col gap-3 min-w-[200px] shrink-0 pt-2 md:pt-0">
                  <button 
                    onClick={() => setSelectedReport(session)}
                    className="flex-1 flex justify-center items-center gap-2 px-6 py-3 bg-white border-2 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-white dark:bg-slate-800 font-medium rounded-xl hover:border-indigo-500 hover:text-indigo-600 dark:hover:border-indigo-500 transition-colors"
                  >
                    <FileText size={16} /> View AI Report
                  </button>
                  <button className="flex-1 flex justify-center items-center gap-2 px-6 py-3 bg-slate-900 text-white dark:bg-white dark:text-slate-900 font-medium rounded-xl hover:bg-slate-800 transition-colors shadow-sm">
                    Consult <ChevronRight size={16} />
                  </button>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
